import jsPDF from 'jspdf';

interface CertificateData {
  studentName: string;
  eventTitle: string;
  eventDate: string;
  organizerName: string;
  certificateNumber: string;
}

export const generateCertificate = async (data: CertificateData): Promise<Blob> => {
  const pdf = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  // Background (certificate border)
  pdf.setDrawColor(16, 185, 129); // Emerald color
  pdf.setLineWidth(2);
  pdf.rect(10, 10, pageWidth - 20, pageHeight - 20);

  pdf.setLineWidth(0.5);
  pdf.setDrawColor(203, 213, 225); // Slate-300
  pdf.rect(15, 15, pageWidth - 30, pageHeight - 30);

  // Header - CampusFlow Logo Text
  pdf.setFontSize(32);
  pdf.setTextColor(16, 185, 129); // Emerald
  pdf.setFont('helvetica', 'bold');
  pdf.text('CampusFlow', pageWidth / 2, 35, { align: 'center' });

  // Certificate Title
  pdf.setFontSize(18);
  pdf.setTextColor(100, 116, 139); // Slate-500
  pdf.setFont('helvetica', 'normal');
  pdf.text('Certificate of Participation', pageWidth / 2, 50, { align: 'center' });

  // Decorative line
  pdf.setLineWidth(0.5);
  pdf.setDrawColor(203, 213, 225);
  pdf.line(80, 55, pageWidth - 80, 55);

  // "This is to certify that"
  pdf.setFontSize(14);
  pdf.setTextColor(100, 116, 139);
  pdf.setFont('helvetica', 'normal');
  pdf.text('This is to certify that', pageWidth / 2, 70, { align: 'center' });

  // Student Name (prominent)
  pdf.setFontSize(28);
  pdf.setTextColor(15, 23, 42); // Slate-900
  pdf.setFont('helvetica', 'bold');
  pdf.text(data.studentName, pageWidth / 2, 85, { align: 'center' });

  // Underline for name
  pdf.setLineWidth(0.3);
  pdf.setDrawColor(203, 213, 225);
  const nameWidth = pdf.getTextWidth(data.studentName);
  pdf.line((pageWidth - nameWidth) / 2, 88, (pageWidth + nameWidth) / 2, 88);

  // "has successfully participated in"
  pdf.setFontSize(14);
  pdf.setTextColor(100, 116, 139);
  pdf.setFont('helvetica', 'normal');
  pdf.text('has successfully participated in', pageWidth / 2, 100, { align: 'center' });

  // Event Title
  pdf.setFontSize(20);
  pdf.setTextColor(15, 23, 42);
  pdf.setFont('helvetica', 'bold');
  pdf.text(data.eventTitle, pageWidth / 2, 115, { align: 'center' });

  // Event Date
  pdf.setFontSize(12);
  pdf.setTextColor(100, 116, 139);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`held on ${data.eventDate}`, pageWidth / 2, 125, { align: 'center' });

  // Certificate Number
  pdf.setFontSize(10);
  pdf.setTextColor(148, 163, 184); // Slate-400
  pdf.text(`Certificate No: ${data.certificateNumber}`, pageWidth / 2, 140, { align: 'center' });

  // Signature Section
  const signatureY = pageHeight - 40;

  // Organizer Signature
  pdf.setLineWidth(0.3);
  pdf.setDrawColor(203, 213, 225);
  pdf.line(40, signatureY, 90, signatureY);
  
  pdf.setFontSize(12);
  pdf.setTextColor(15, 23, 42);
  pdf.setFont('helvetica', 'bold');
  pdf.text(data.organizerName, 65, signatureY + 7, { align: 'center' });
  
  pdf.setFontSize(10);
  pdf.setTextColor(100, 116, 139);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Event Organizer', 65, signatureY + 13, { align: 'center' });

  // Admin/Principal Signature
  pdf.setLineWidth(0.3);
  pdf.line(pageWidth - 90, signatureY, pageWidth - 40, signatureY);
  
  pdf.setFontSize(12);
  pdf.setTextColor(15, 23, 42);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Campus Admin', pageWidth - 65, signatureY + 7, { align: 'center' });
  
  pdf.setFontSize(10);
  pdf.setTextColor(100, 116, 139);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Authorized Signatory', pageWidth - 65, signatureY + 13, { align: 'center' });

  // Footer
  pdf.setFontSize(9);
  pdf.setTextColor(148, 163, 184);
  pdf.text('Generated by CampusFlow Event Management System', pageWidth / 2, pageHeight - 10, { align: 'center' });

  // Return as Blob
  return pdf.output('blob');
};

export const downloadCertificate = async (data: CertificateData, filename: string) => {
  const blob = await generateCertificate(data);
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
